#!/usr/bin/env sh

##############################################################################
## Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use this file to customize the JVM options.
DEFAULT_JVM_OPTS=''

# Use the GRADLE_HOME environment variable if set.
if [ -n "$GRADLE_HOME" ]; then
  GRADLE_HOME="$GRADLE_HOME"
fi

# Attempt to locate a JDK.
if [ -n "$JAVA_HOME" ]; then
  JAVA_HOME="$JAVA_HOME"
fi

# For Cygwin or MSYS, use appropriate options.
if [ -n "$MSYS" ]; then
  case "$MSYS" in
    msys*)
      APP_HOME=$(cygpath --path --windows "$APP_HOME")
      ;;
  esac
fi

APP_HOME=$(CDPATH= cd -- "$APP_HOME" && pwd)

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the Gradle daemon.
if [ -n "$JAVA_HOME" ]; then
  JAVA_EXE="$JAVA_HOME/bin/java"
else
  JAVA_EXE=$(command -v java)
fi

if [ ! -x "$JAVA_EXE" ]; then
  echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
  echo "Please set JAVA_HOME or add java to your PATH."
  exit 1
fi

exec "$JAVA_EXE" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
